CREATE TABLE IF NOT EXISTS document (
  DocumentId BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  DocumentPath VARCHAR(256) NOT NULL,
  DocumentName VARCHAR(120) DEFAULT NULL,
  DisplayName VARCHAR(120) DEFAULT NULL,
  DocumentExtension VARCHAR(10) DEFAULT NULL,
  CreatedById INT(10) UNSIGNED DEFAULT NULL,
  CreatedDate DATETIME DEFAULT NULL,
  ModifiedById INT(10) UNSIGNED DEFAULT NULL,
  ModifiedDate DATETIME DEFAULT NULL,
  Active BIT(1) NOT NULL DEFAULT b'1',
  PRIMARY KEY (DocumentId)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_unicode_ci;